# Generated by Django 2.2.3 on 2019-07-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_master_users',
            name='entry_time',
            field=models.DateTimeField(),
        ),
    ]
