# Generated by Django 2.2.3 on 2019-07-22 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20190721_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_master_users',
            name='password',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temp_master_users',
            name='username',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
