# Generated by Django 2.2.3 on 2019-07-22 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20190722_0349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temp_master_users',
            name='is_available',
        ),
    ]
