# Generated by Django 2.2.3 on 2019-09-04 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_remove_temp_master_users_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_groups',
            name='group_admin',
            field=models.CharField(default='admin', max_length=255),
            preserve_default=False,
        ),
    ]
