# Generated by Django 2.2.3 on 2019-09-04 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_auto_20190904_0413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master_groups',
            name='group_admin',
        ),
    ]
