# Generated by Django 2.2.3 on 2019-09-04 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_remove_master_groups_group_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_groups',
            name='group_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.Master_Users'),
        ),
    ]
