# Generated by Django 2.2.3 on 2020-01-07 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_master_groups_group_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_master_users',
            name='user_type_id',
            field=models.SmallIntegerField(default=3),
        ),
    ]
