# Generated by Django 2.2.3 on 2020-01-22 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_auto_20200107_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_groups',
            name='group_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.Master_Users'),
        ),
        migrations.AlterField(
            model_name='user_credentials',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.Master_Users'),
        ),
        migrations.AlterField(
            model_name='user_group_mapping',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.Master_Groups'),
        ),
        migrations.AlterField(
            model_name='user_group_mapping',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.Master_Users'),
        ),
    ]
