# Generated by Django 2.2.3 on 2020-01-24 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_auto_20200122_0349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master_Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.SmallIntegerField()),
                ('plan_name', models.CharField(max_length=50)),
                ('no_days', models.SmallIntegerField(default=0, null=True)),
                ('count', models.SmallIntegerField(default=0, null=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Subscription_Mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('exam_count', models.SmallIntegerField(null=True)),
                ('subs_val', models.BooleanField(default=True)),
                ('subcription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.Master_Subscription')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.Master_Users')),
            ],
        ),
    ]
