# Generated by Django 2.2.3 on 2020-01-27 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_auto_20200127_0409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_subscription_mapping',
            old_name='subcription',
            new_name='subscription',
        ),
    ]
