# Generated by Django 2.2.3 on 2019-07-17 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Topics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.SmallIntegerField()),
                ('question_text', models.TextField()),
                ('question_marks', models.FloatField()),
                ('difficulty', models.SmallIntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('subtopic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Topics.Master_SubTopic')),
            ],
        ),
        migrations.CreateModel(
            name='Master_Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=500)),
                ('is_available', models.BooleanField(default=True)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Questions.Master_Question')),
            ],
        ),
        migrations.CreateModel(
            name='Master_Correct_Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Questions.Master_Option')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Questions.Master_Question')),
            ],
        ),
    ]
