# Generated by Django 2.2.3 on 2020-01-22 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_correct_option',
            name='option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Questions.Master_Option'),
        ),
        migrations.AlterField(
            model_name='master_correct_option',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Questions.Master_Question'),
        ),
        migrations.AlterField(
            model_name='master_option',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Questions.Master_Question'),
        ),
        migrations.AlterField(
            model_name='master_question',
            name='subtopic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Topics.Master_SubTopic'),
        ),
    ]
