# Generated by Django 2.2.3 on 2019-07-17 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Template', '0001_initial'),
        ('Questions', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master_Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=255)),
                ('exam_duration', models.TimeField()),
                ('show_result_immediately', models.BooleanField(default=False)),
                ('result_timestamp', models.DateTimeField()),
                ('exam_enable_time', models.DateTimeField()),
                ('is_enable', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.Master_Groups')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Template.Master_Template')),
            ],
        ),
        migrations.CreateModel(
            name='User_Question_Assigned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Exams.Master_Exam')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Questions.Master_Question')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Template.Master_Section')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.Master_Users')),
            ],
        ),
        migrations.CreateModel(
            name='User_Test_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField()),
                ('duration', models.IntegerField()),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Exams.Master_Exam')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.Master_Users')),
            ],
        ),
        migrations.CreateModel(
            name='User_Question_Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Questions.Master_Option')),
                ('section_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Exams.User_Question_Assigned')),
            ],
        ),
    ]
