# Generated by Django 2.2.3 on 2019-12-03 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exams', '0002_user_question_response_marked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_exam',
            name='exam_duration',
            field=models.IntegerField(),
        ),
    ]
