# Generated by Django 2.2.3 on 2019-12-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exams', '0003_auto_20191203_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_test_status',
            name='attempts',
            field=models.SmallIntegerField(default=3),
        ),
    ]
