# Generated by Django 2.2.3 on 2019-09-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Template', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template_section',
            name='difficulty_id',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template_section',
            name='no_questions',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
