# Generated by Django 2.2.3 on 2019-09-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Template', '0002_auto_20190923_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_section',
            name='section_duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='master_template',
            name='template_duration',
            field=models.IntegerField(),
        ),
    ]
