# Generated by Django 2.2.3 on 2020-01-22 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Template', '0003_auto_20190928_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_section',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Template.Master_Template'),
        ),
        migrations.AlterField(
            model_name='template_section',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Template.Master_Section'),
        ),
        migrations.AlterField(
            model_name='template_section',
            name='subtopic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Topics.Master_SubTopic'),
        ),
    ]
